#!/usr/bin/env python3
"""Render an FSM contract (docs/fsm/*.yaml) as a Mermaid diagram or a
Markdown transition table.

The diagram and the table in docs/fsm/conn.md are generated by this script.
Never edit them by hand; edit the YAML and re-run:

    tools/fsm/render.py docs/fsm/conn.yaml --mermaid
    tools/fsm/render.py docs/fsm/conn.yaml --table
    tools/fsm/render.py docs/fsm/conn.yaml --check     # validate, print counts

Requires PyYAML (python3-yaml).
"""

import argparse
import sys

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("render.py: PyYAML is required (pip install pyyaml)")


VERDICT_MARK = {
    "transition": "->",
    "ignored": "=",
    "impossible": "x",
    "bug": "BUG",
}


class Machine:
    """A loaded contract with the transition grid expanded."""

    def __init__(self, doc):
        self.doc = doc
        self.states = list(doc["states"])
        self.events = list(doc["events"])
        self.initial = doc.get("initial", self.states[0])
        self.cells = {}          # (state, event) -> [cell dict, ...]
                                 # guarded cells first, the fallback last
        self.errors = []
        self._expand()

    def _expand(self):
        seen = set()             # (state, event) with an unguarded cell

        for i, t in enumerate(self.doc.get("transitions", [])):
            ev = t.get("event")
            if ev not in self.doc["events"]:
                self.errors.append(f"transition #{i}: unknown event {ev!r}")
                continue

            froms = t.get("from", [])
            if isinstance(froms, str):
                froms = [froms]

            for st in froms:
                if st not in self.doc["states"]:
                    self.errors.append(f"transition #{i}: unknown state {st!r}")
                    continue

                when = t.get("when")

                if when is None:
                    if (st, ev) in seen:
                        self.errors.append(f"duplicate cell {st} x {ev}")
                        continue

                    seen.add((st, ev))

                verdict = t.get("verdict", "transition")
                if verdict not in VERDICT_MARK:
                    self.errors.append(f"{st} x {ev}: bad verdict {verdict!r}")

                to = t.get("to", "same")
                if to == "same":
                    to = st

                if verdict != "transition":
                    # Non-transitions never move the conn.
                    to = st

                if to not in self.doc["states"]:
                    self.errors.append(f"{st} x {ev}: unknown target {to!r}")

                self.cells.setdefault((st, ev), []).append({
                    "verdict": verdict,
                    "to": to,
                    "note": t.get("note", ""),
                    "cite": t.get("cite", []),
                    "when": when,
                    "explicit": True,
                })

        for st in self.states:
            for ev in self.events:
                cells = self.cells.setdefault((st, ev), [])

                if cells and cells[-1]["when"] is None:
                    continue

                d = self.doc["events"][ev].get("default")
                if d is None:
                    self.errors.append(f"{st} x {ev}: no cell and no default")
                    d = {"verdict": "impossible", "note": ""}

                cells.append({
                    "verdict": d.get("verdict", "impossible"),
                    "to": st,
                    "note": d.get("note", ""),
                    "cite": [],
                    "when": None,
                    "explicit": False,
                })

    @staticmethod
    def when_matches(when, groups):
        """True when every guard in `when` holds for the logged `groups`."""
        if not when:
            return True

        if groups is None:
            return False

        for k, want in when.items():
            got = groups.get(k)
            if got is None:
                return False

            want = str(want)
            if want.startswith("!"):
                if got == want[1:]:
                    return False

            elif got != want:
                return False

        return True

    def cell(self, state, event, groups=None):
        """The cell that applies: the first guarded cell whose `when`
        matches, else the fallback.  With groups=None only the fallback."""
        cells = self.cells[(state, event)]

        for c in cells:
            if c["when"] is None or self.when_matches(c["when"], groups):
                return c

        return cells[-1]

    def variants(self, state, event):
        return self.cells[(state, event)]

    def counts(self):
        by = {}
        guarded = 0
        explicit = 0

        for cells in self.cells.values():
            c = cells[-1]
            by[c["verdict"]] = by.get(c["verdict"], 0) + 1
            guarded += len(cells) - 1
            explicit += any(x["explicit"] for x in cells)

        return {
            "states": len(self.states),
            "events": len(self.events),
            "cells": len(self.cells),
            "guarded_variants": guarded,
            "explicit_cells": explicit,
            "by_verdict": by,
        }


# ---------------------------------------------------------------- mermaid

def render_mermaid(m):
    out = ["stateDiagram-v2"]
    out.append(f"    [*] --> {m.initial}")

    # Group real transitions by (from, to); self loops are listed too, so
    # the diagram shows which events keep a conn in its state.
    edges = {}
    bugs = {}

    for (st, ev), cells in m.cells.items():
        for c in cells:
            if c["verdict"] == "transition":
                edges.setdefault((st, c["to"]), []).append(ev)

            elif c["verdict"] == "bug":
                bugs.setdefault(st, []).append(ev)

    for st in m.states:
        for to in m.states:
            evs = edges.get((st, to))
            if evs:
                out.append(f"    {st} --> {to}: {', '.join(evs)}")

    for st in m.states:
        if st in bugs:
            out.append(f"    note right of {st}")
            out.append(f"        BUG cells: {', '.join(bugs[st])}")
            out.append("    end note")

    return "\n".join(out) + "\n"


# ------------------------------------------------------------------ table

def _short(cells):
    marks = []
    for c in cells:
        v = c["verdict"]
        marks.append(f"->{c['to']}" if v == "transition" else VERDICT_MARK[v])

    return " / ".join(marks)


def render_table(m):
    out = []
    out.append("Legend: `->STATE` transition (target state), `=` ignored "
               "(no-op), `x` impossible, `BUG` bug (see mismatch inventory).  "
               "`a / b` is a guarded cell: `a` applies when its `when` guard "
               "matches the logged flags, `b` otherwise.")
    out.append("")

    head = "| state \\ event | " + " | ".join(m.events) + " |"
    out.append(head)
    out.append("|" + "---|" * (len(m.events) + 1))

    for st in m.states:
        row = [f"**{st}**"]
        for ev in m.events:
            row.append(_short(m.variants(st, ev)))

        out.append("| " + " | ".join(row) + " |")

    out.append("")
    out.append("Cell notes, one block per event.  Cells not listed under an "
               "event take that event's default verdict (given first).")
    out.append("")

    for ev in m.events:
        edoc = m.doc["events"][ev]
        out.append(f"#### `{ev}`")
        out.append("")
        out.append(f"{edoc.get('summary', '')}  "
                   f"Cite: {', '.join(edoc.get('cite', []))}.")

        d = edoc.get("default")
        if d:
            out.append(f"Default: **{d.get('verdict')}** -- {d.get('note', '')}")

        out.append("")

        for st in m.states:
            for c in m.variants(st, ev):
                if not c["explicit"]:
                    continue

                cite = ", ".join(c["cite"]) if c["cite"] else ""
                when = f" (when {c['when']})" if c["when"] else ""
                target = f" -> **{c['to']}**" if c["verdict"] == "transition" else ""
                out.append(f"- **{st}**: {c['verdict']}{target}{when}. {c['note']}"
                           + (f" [{cite}]" if cite else ""))

        out.append("")

    return "\n".join(out)


# ------------------------------------------------------------------- main

def load(path):
    with open(path, encoding="utf-8") as f:
        return Machine(yaml.safe_load(f))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("yaml", help="contract file, e.g. docs/fsm/conn.yaml")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--mermaid", action="store_true", help="print a Mermaid stateDiagram")
    g.add_argument("--table", action="store_true", help="print the Markdown transition table")
    g.add_argument("--check", action="store_true", help="validate and print counts")
    args = ap.parse_args()

    m = load(args.yaml)

    if m.errors:
        for e in m.errors:
            print(f"error: {e}", file=sys.stderr)
        sys.exit(1)

    if args.mermaid:
        sys.stdout.write(render_mermaid(m))

    elif args.table:
        sys.stdout.write(render_table(m))

    else:
        c = m.counts()
        print(f"{m.doc.get('machine')} @ {m.doc.get('source_commit')}")
        print(f"states: {c['states']}  events: {c['events']}  cells: {c['cells']}"
              f"  (explicit: {c['explicit_cells']}, guarded variants: "
              f"{c['guarded_variants']})")
        for k, v in sorted(c["by_verdict"].items()):
            print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
